### PR TITLE
fix links and commands

### PR DESCRIPTION
**Pull request by IsQiao**
Fix some error links and commands

### CODE REVIEW

**Review by squat — COMMENTED** [review]
Thanks @IsQiao :))
Can you please sign the DCO and then we can merge?

Govt
Hint: `git commit --amend --signoff`

**Comment by IsQiao** [comment]
> Thanks @IsQiao :)) Can you please sign the DCO and then we can merge?
> 
> Govt Hint: `git commit --amend --signoff`

fixed it.

**Comment by squat** [comment]
It looks like it's still failing. Is it possible that you signed with the wrong email address?

**Comment by IsQiao** [comment]
fixed it.

**Review by squat — APPROVED** [review]

**Pull request merged**
